version: "3.7"

services:
  api:
    image: node:12-alpine
    container_name: api
    ports:
      - "3000:3000"
      - "587:587"
    volumes:
      - ./api:/data
    working_dir: /data
    networks:
      - boilerplate-network
    command: ./node_modules/.bin/nodemon

  web:
    image: node:12-alpine
    container_name: web
    ports:
      - "80:3000"
    volumes:
      - ./web:/data
    working_dir: /data
    networks:
      - boilerplate-network
    command: npm start

networks:
  boilerplate-network:
